title: 'News list'
breadcrumb:
    index:
        label: 'News list'
        action: 'index'

search: 'true'

formPanelProperties:
    headerLabel: 'Filter news'
    formFields:
        name:
            label: 'Name'
            conditionField: 'name'
            type: 'text'
            conditionType: 'like'
            col: '4'
        startCreated:
            label: 'Created >='
            conditionField: 'created'
            type: 'datetime'
            conditionType: 'superiorOrEqual'
            col: '4'
        endCreated:
            label: 'Created <='
            conditionField: 'created'
            type: 'datetime'
            conditionType: 'inferiorOrEqual'
            col: '4'
    footerListButtons:
        submit:
            buttonType: 'button'
            label: 'Filter'

tablePanelProperties:
    headerLabel: 'News list'
    headerListButtons:
        create:
            buttonType: 'link'
            color: 'success'
            label: 'Create a news'
            action: 'create'
            modal: 'true'
            size: 'xs'
    tableFields:
        buttons:
            multipleFields:
            view:
                icon: 'eye'
                action: 'view'
                color: 'info'
                target: '_blank'
            update:
                icon: 'pencil'
                action: 'update'
            delete:
                icon: 'trash'
                color: 'danger'
                action: 'delete'
                confirm: 'Do you really want to delete this news ?'
        id:
        name:
        created:
            type: 'date'
            dateFormat: 'd/m/Y H:i:s'
