title: 'Créer une actualité'

formFields:
    - name

footerFormFields:
    create:
        label: 'Créer'
        field: 'create'
        color: 'success'
    createEdit:
        label: 'Créer & Editer'
        field: 'createEdit'