title: 'Create a news'

formFields:
    - name

footerFormFields:
    create:
        label: 'Create'
        field: 'create'
        color: 'success'
    createEdit:
        label: 'Create & Edit'
        field: 'createEdit'