actions:
    index:
        route: 'bk_wh_blog_post_index'
    create:
        route: 'bk_wh_blog_post_create'
    update:
        route: 'bk_wh_blog_post_update'
        parameters:
            id: 'id'
    delete:
        route: 'bk_wh_blog_post_delete'
        parameters:
            id: 'id'

formFields:
    id:
        label: 'ID'
    name:
        label: 'Nom'
        field: 'name'
        type: 'text'
    title:
        label: 'Titre'
        field: 'title'
        type: 'text'
    resume:
        label: 'Résumé'
        field: 'resume'
        type: 'textarea'
    body:
        label: 'Contenu'
        field: 'body'
        type: 'tinymce'
    thumb:
        label: 'Vignette'
        field: 'thumb'
        type: 'amazon_s3_file'
#        class: 'WHAmazonS3MediaBundle:File'
#        choice_label: 'fileName'
#        attr:
#            class: 'amazon-file'
    status:
        label: 'Etat'
        type : 'choice'
        options:
            type: 'static'
            field: 'statuses'

menus:
    main: 'menu-admin'
    right: 'menu-admin-right'