actions:
    index:
        route: 'bk_wh_blog_post_index'
    create:
        route: 'bk_wh_blog_post_create'
    update:
        route: 'bk_wh_blog_post_update'
        parameters:
            id: 'id'
    delete:
        route: 'bk_wh_blog_post_delete'
        parameters:
            id: 'id'
    view:
        route: 'ft_wh_seo_router_dispatch'
        parameters:
            url: 'url.url'

formFields:
    id:
        label: 'ID'
    name:
        label: 'Nom'
        field: 'name'
        type: 'text'
    title:
        label: 'Titre'
        field: 'title'
        type: 'text'
    resume:
        label: 'Résumé'
        field: 'resume'
        type: 'textarea'
    body:
        label: 'Contenu'
        field: 'body'
        type: 'tinymce'
    thumb:
        label: 'Vignette'
        field: 'thumb'
        type: 'wh_file'
    status:
        label: 'Etat'
        type : 'choice'
        options:
            type: 'static'
            field: 'statuses'
    metas:
        type: 'form'
        form: 'WH\SeoBundle\Form\Backend\MetasType'

menus:
    main: 'backend-menu'
    right: 'backend-menu-right'