actions:
    index:
        route: 'bk_wh_blog_post_index'
    create:
        route: 'bk_wh_blog_post_create'
    update:
        route: 'bk_wh_blog_post_update'
        parameters:
            id: 'id'
    delete:
        route: 'bk_wh_blog_post_delete'
        parameters:
            id: 'id'
    view:
        route: 'ft_wh_seo_router_dispatch'
        parameters:
            url: 'url.url'

formFields:
    id:
        label: 'ID'
    name:
        label: 'Name'
        field: 'name'
        type: 'text'
    title:
        label: 'Title'
        field: 'title'
        type: 'text'
    resume:
        label: 'Resume'
        field: 'resume'
        type: 'textarea'
    body:
        label: 'Content'
        field: 'body'
        type: 'tinymce'
    thumb:
        label: 'Thumb'
        field: 'thumb'
        type: 'wh_file'
    status:
        label: 'Status'
        type : 'choice'
        options:
            type: 'static'
            field: 'statuses'
    metas:
        type: 'form'
        form: 'WH\SeoBundle\Form\Backend\MetasType'

menus:
    main: 'backendMenu'
    right: 'backendMenuRight'