title: 'Liste des actualités'
breadcrumb:
    index:
        label: 'Liste des actualités'
        action: 'index'

search: 'true'

formPanelProperties:
    headerLabel: 'Filtrer les actualités'
    formFields:
        name:
            label: 'Nom'
            field: 'name'
            type: 'text'
            conditionType: 'like'
            col: '6'
    footerListButtons:
        submit:
            buttonType: 'button'
            label: 'Filtrer'

tablePanelProperties:
    headerLabel: 'Liste des actualités'
    headerListButtons:
        create:
            buttonType: 'link'
            color: 'success'
            label: 'Créer une actualité'
            action: 'create'
            modal: 'true'
            size: 'xs'
    tableFields:
        buttons:
            update:
                icon: 'pencil'
                action: 'update'
            delete:
                icon: 'trash'
                color: 'danger'
                action: 'delete'
                confirm: 'Êtes-vous sûr de vouloir supprimer cette actualité ?'
        id:
        name:
