title: 'News list'
breadcrumb:
    index:
        label: 'News list'
        action: 'index'

search: 'true'

formPanelProperties:
    headerLabel: 'Filter news'
    formFields:
        name:
            label: 'Name'
            field: 'name'
            type: 'text'
            conditionType: 'like'
            col: '6'
    footerListButtons:
        submit:
            buttonType: 'button'
            label: 'Filter'

tablePanelProperties:
    headerLabel: 'News list'
    headerListButtons:
        create:
            buttonType: 'link'
            color: 'success'
            label: 'Create a news'
            action: 'create'
            modal: 'true'
            size: 'xs'
    tableFields:
        buttons:
            multipleFields:
            view:
                icon: 'eye'
                action: 'view'
                color: 'info'
                target: '_blank'
            update:
                icon: 'pencil'
                action: 'update'
            delete:
                icon: 'trash'
                color: 'danger'
                action: 'delete'
                confirm: 'Êtes-vous sûr de vouloir supprimer cette actualité ?'
        id:
        name:
